$DT_PORTAL_INSECURE_BASE_URL = 'http://secure-test.ifbyphone.com'
$DT_PORTAL_SECURE_BASE_URL = 'https://secure-test.ifbyphone.com'
$DT_PORTAL_USERNAME = 'capybara'
$DT_PORTAL_PASSWORD = 'Ifbyphone'
$DT_EMAIL_ADDRESS = 'mcarroll@dialogtech.com'